version: "3"
services:
  node-app:
    container_name: wordhalp
    restart: "unless-stopped"
    build: .
    ports:
      - "4001:8081"
    volumes:
      - /usr/app/node_modules
      #- .:/usr/app
